### PR TITLE
always activate default conda environment

### PR DESCRIPTION
**Pull request by nuest**
Suggestion for fixing #698 - feedback by conda expert needed :-)

### CODE REVIEW

**Comment by nuest** [comment]
Note the tests also changed. Is is a problem that Python 3 is not listed as a kernel anymore? :thinking:

**Comment by meeseeksmachine** [comment]
This pull request has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/creating-environment-yml-for-python-2-via-binder/1609/7

**Comment by minrk** [comment]
> Is is a problem that Python 3 is not listed as a kernel anymore? 🤔

Possibly. We'll need to be careful with this one if the kernel env is unconditionally first on PATH. Make sure this case is tested: the `notebook` package is installed in both envs and the notebook env is the one that's used. I'm pretty sure this won't be the case because we launch `jupyter notebook ...` relying on PATH to resolve correctly. If we switched the launch command to $NB_PYTHON_PREFIX/bin/jupyter-notebook, it would probably be correct, but wouldn't be as portable to e.g. Dockerfile builds that can use different paths.

The alternative is to try to fix more directly, and make sure that env activation is different for subprocesses of the notebook vs the notebook process. This can be achieved by performing some custom startup in the notebook process and/or entrypoint that's not reflected by terminal subprocesses

**Comment by nuest** [comment]
@minrk Thanks for your comment, though I have to admit I am bit out of my depth here, if the fix is not as simple as it seemed to me.

_Which approach do you think is worth trying out: switching the launch command, or activate envs?_

With the changes in this PR, I get the following:

```
daniel@687f78fd20b2:~$ conda env list
# conda environments:
#
base                     /srv/conda
notebook              *  /srv/conda/envs/notebook

daniel@687f78fd20b2:~$ /srv/conda/bin/python --version
Python 3.7.3
daniel@687f78fd20b2:~$ /srv/conda/envs/notebook/bin/python --version
Python 2.7.15
daniel@687f78fd20b2:~$ echo $KERNEL_PYTHON_PREFIX
/srv/conda/envs/notebook
daniel@687f78fd20b2:~$ echo $NB_PYTHON_PREFIX
/srv/conda/envs/notebook
daniel@687f78fd20b2:~$ echo $PATH
/srv/conda/envs/notebook/bin:/home/daniel/pcraster/bin:/srv/conda/envs/notebook/bin:/srv/conda/condabin:/home/daniel/.local/bin:/home/daniel/.local/bin:/srv/conda/envs/notebook/bin:/srv/conda/bin:/srv/npm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
daniel@687f78fd20b2:~$ ls /srv/conda/envs/
notebook
```

- The base environment does _not_ have the `notebook` package.
- `$KERNEL_PYTHON_PREFIX` is the same as `$NB_PYTHON_PREFIX`, namely `/srv/conda/envs/notebook`

Re. "the notebook package is installed in both envs and the notebook env is the one that's used.": There are no "both" envs. Is that an issue, i.e. should the Notebook always run Python 3, and the kernel be configurable by the user?

Should it be possible to have multiple Python versions and environments?

--------

**Related question:** For clarity, could the `CMD ["jupyter", "notebook", "--ip", "0.0.0.0"]` in the template in `base.py` be removed, because the `if not self.run_cmd` - code `app.py` will either override the command or use the custom one provided by the user? Or is the one in `base.py` the one for running the image on JupyterHub, and the one created in `app.py` the one for local use? :confused:

**Comment by consideRatio** [comment]
Currently, you can get python2 by writing `python2`, or open a python2 kernel.

image

Since this PR didn't resolve in the last three years, and python2 is even more outdated now, I think this behavior suffice and its more pressing to ensure sustainable maintenance of repo2docker as a project by not making it more complicated.

I'll go for a close for now, but feel free to open it again!

**Pull request closed without merging**
