### PR TITLE
[WIP] Demo rstudio package manager integration

### PR DESCRIPTION
**Pull request by kkmann**
# Summary

Demo PR for experimenting with the new RStudio package manager R package binaries, see #925 

# (Known) open issues 
- [ ] implement cutoff date for switching from MRAN to RSPM

### CODE REVIEW

**Comment by kkmann** [comment]
if I understand the test correct, it's failing because the snapshot date is very old (2017) and packagemanager.rstudio is not reliable - just need to switch back to MRAN before say 2020-06-01

**Comment by yuvipanda** [comment]
Wah, I was just going to find and implement this. I think this is the way to go! Let's pick a cut-off date and be done.

**Comment by yuvipanda** [comment]
I think this is superseeded by https://github.com/jupyterhub/repo2docker/pull/1104

**Comment by manics** [comment]
As mentioned in the previous comment this is done in https://github.com/jupyterhub/repo2docker/pull/1104

**Pull request closed without merging**
