### PR TITLE
always unpack a single zenodo zip

### LINKED ISSUE #1042: Always unpack single zip files from Zenodo
### Proposed change

Uploading a .zip is the only way to represent folders on zenodo. It is also what zenodo does on github imports.

[Right now](https://github.com/jupyterhub/repo2docker/blob/master/repo2docker/contentproviders/zenodo.py#L71) repo2docker will only unpack the zip if DOI is marked as being software. I propose to unpack a single file unconditionally instead. The motivation is as follows:

- Some uploads containing both software and data (e.g. processing scripts) may classify themselves as datasets.
- If the user is facing a binder with a single zip file, their likely first step is to unzip said file.

The only downside I can think of is hitting disk space limits, however the workaround is trivial: the repository owner then needs to upload more than a single zip file. At the same time, currently the repository owner needs to choose any 2 out of the following 3 options:

- Having folders
- Having a functional binder
- Not labeling the repo as software

### Alternative options

Keep everything as it is...

### Who would use this feature?

Zenodo users

### How much effort will adding it take?

No effort (editing 2 lines), I'm about to open a PR.

### Who can do this work?

I can!

### PR DESCRIPTION
**Pull request by akhmerov**
Closes #1042 (see discussion there).

### CODE REVIEW

**Comment by akhmerov** [comment]
Docs failure is unrelated :(

**Comment by yuvipanda** [comment]
If you add a test pointing to an appropriate zenodo DOI that will be extracted, am happy to merge this!

If you rebase, the docs failure should be gone now

**Comment by akhmerov** [comment]
Please take a look, I've rebased and adjusted an existing test.

**Comment by yuvipanda** [comment]
\o/ thanks a lot, @akhmerov! I'll try deploy this later today

**Comment by yuvipanda** [comment]
@akhmerov deployed now! Can you test it out?

**Comment by akhmerov** [comment]
Yep, works just as expected! Thanks!

**Comment by yuvipanda** [comment]
Thanks a lot, @akhmerov!

**Pull request merged**
