### PR TITLE
notebook 7

### LINKED ISSUE #1361: Can't access server with provided token
```
$ repo2docker --version
2024.07.0
$ repo2docker .
...
Successfully tagged r2d-2e1722612782:latest
/srv/conda/envs/notebook/lib/python3.10/subprocess.py:961: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
[I 15:35:10.721 NotebookApp] Writing notebook server cookie secret to /home/raniere/.local/share/jupyter/runtime/notebook_cookie_secret

  _   _          _      _
 | | | |_ __  __| |__ _| |_ ___
 | |_| | '_ \/ _` / _` |  _/ -_)
  \___/| .__/\__,_\__,_|\__\___|
       |_|
                       
Read the migration plan to Notebook 7 to learn about the new features and the actions to take if you are using extensions.

https://jupyter-notebook.readthedocs.io/en/latest/migrate_to_notebook7.html

Please note that updating to Notebook 7 might break some of your extensions.

[W 2024-08-02 15:35:11.386 LabApp] 'ip' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2024-08-02 15:35:11.386 LabApp] 'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2024-08-02 15:35:11.386 LabApp] 'custom_display_url' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2024-08-02 15:35:11.386 LabApp] 'custom_display_url' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2024-08-02 15:35:11.386 LabApp] 'custom_display_url' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[I 2024-08-02 15:35:11.396 LabApp] JupyterLab extension loaded from /srv/conda/envs/notebook/lib/python3.10/site-packages/jupyterlab
[I 2024-08-02 15:35:11.396 LabApp] JupyterLab application directory is /srv/conda/envs/notebook/share/jupyter/lab
[I 2024-08-02 15:35:11.397 LabApp] Extension Manager is 'pypi'.
[I 15:35:11.410 NotebookApp] Serving notebooks from local directory: /home/raniere
[I 15:35:11.410 NotebookApp] Jupyter Notebook 6.5.6 is running at:
[I 15:35:11.410 NotebookApp] http://127.0.0.1:44781/?token=7dd7de0ba3280d147c16fed90617b006cdea0c65ce55c54f
[I 15:35:11.410 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 15:35:11.413 NotebookApp] No web browser found: could not locate runnable browser.
[C 15:35:11.413 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///home/raniere/.local/share/jupyter/runtime/nbserver-14-open.html
    Or copy and paste this URL:
        http://127.0.0.1:44781/?token=7dd7de0ba3280d147c16fed90617b006cdea0c65ce55c54f
```

#### Expected behaviour

http://127.0.0.1:44781/?token=7dd7de0ba3280d147c16fed90617b006cdea0c65ce55c54f will give access Jupyter Lab.

#### Actual behaviour

http://127.0.0.1:44781/?token=7dd7de0ba3280d147c16fed90617b006cdea0c65ce55c54f asks for the token

Screenshot 2024-08-02 at 17-42-00 Jupyter Notebook

### Your personal set up

- OS: Ubuntu running on WLS2
- Docker version: Docker version 26.0.0, build 2ae903e
- repo2docker version: 2024.07.0

### PR DESCRIPTION
**Pull request by minrk**
closes #1302
closes #1361

#1340 upgraded to jupyterlab 4 and jupyter-server 2, but that created #1361 because the classic notebook server auth isn't compatible with jupyter-server-based extensions and jupyter-server 2's IdentityProvider (https://github.com/jupyter-server/jupyter_server/pull/1221). This is a problem because the default command is `jupyter notebook --NotebookApp.default_url=/lab`, i.e. launch classic notebook server with JupyterLab UI, which won't work. 

If we want a smaller fix to make a patch release, it would be to switch the default server command to jupyter-server. Classic notebook UI with jupyter-server 2 _will_ work via `nbclassic`, but classic notebook server with jupyter-server Extensions will not.

### CODE REVIEW

**Comment by manics** [comment]
https://github.com/jupyterhub/repo2docker/blob/388c9341f3d70882233a894e9b03f06eb17884ad/tests/venv/binder-dir/verify#L5-L6
also needs to be changed

**Review by manics — APPROVED** [review]

**Comment by minrk** [comment]
Coming back to this, anything to pre-announce, or go ahead and merge and announce?

**Comment by manics** [comment]
I think giving advanced warning on https://discourse.jupyter.org/ would be nice, e.g. a couple of weeks? How about something along these lines:

> Notebook 7 was released [a year ago](https://blog.jupyter.org/announcing-jupyter-notebook-7-8d6d66126dcf), and we're planning to upgrade the default version of notebook on mybinder in a couple of weeks. Notebook 7 is based on the same underlying components as JupyterLab, so extensions designed for Notebook 6 and earlier will need to be updated.

Can we provide instructions for using the old notebook? E.g.
> If you need the previous version of Jupyter notebook you should add `notebook==6` to your `requirements.txt` or `notebook=6` to your `environment.yml` file.

Or should we tell people to install nbclassic so we can run jupyter-server?

**Comment by minrk** [comment]
Makes sense. It may be a bit tricky, since notebook 6 not actually working is the reason for this bump (#1361). notebook 6 + server 2 don't _quite_ work together, though if you only use one and specify the right launch command, thigs will _probably_ work, unless you have ~any extensions.

So it would probably be better to specify notebook 6 _and_ server 1, which will downgrade lab, too, I think, and possibly have other consequences.

**Comment by manics** [comment]
How about this text?

---

Notebook 7 was released [a year ago](https://blog.jupyter.org/announcing-jupyter-notebook-7-8d6d66126dcf), and we're planning to upgrade the default version of notebook on mybinder.org in a couple of weeks. Notebook 7 is based on the same underlying components as JupyterLab, so extensions designed for Notebook 6 and earlier will need to be updated.

If you need the previous version of Jupyter notebook you should install `notebook 6.*` and `jupyter-server 1.*`. For example:

`requirements.txt`:
```txt
notebook==6
jupyter-server==1
```
`environment.yml`:
```
name: example-environment
channels:
  - conda-forge
dependencies:
  - notebook=6
  - jupyter_server=1
```

This may change the installed version of JupyterLab, so only do this if you need the old version of notebook and do not need JupyterLab.

**Comment by minrk** [comment]
That looks great. Let's test it to make sure it actually works, if you haven't already, then we can post it.

**Comment by minrk** [comment]
The conda version works, but pip doesn't actually downgrade packages broken by the downgrade of notebook/server, it just warns about unsatisfied dependencies, so `requirements.txt` requires `jupyterlab==3.*` explicitly. The result would be a broken env on mybinder.org, which launches `/lab`.

**Comment by manics** [comment]
Thanks for checking! Do you want to post the announcement on Discourse? Otherwise I'm happy to.

**Comment by minrk** [comment]
I actually have to step out for a bit right now, so if you could that would be great. Otherwise, I can do it when I get back this afternoon.

**Comment by manics** [comment]
Done! https://discourse.jupyter.org/t/notebook-7-on-mybinder-org-and-repo2docker/27924

**Pull request merged**
