### PR TITLE
Remove support for deprecated Julia REQUIRE, Julia < 1.3

### LINKED ISSUE #1349: Julia tests are failing
### Bug description
These Julia tests are failing:
- `tests/julia/project-1.0.2-binder-dir`
- `tests/julia/require`
- `tests/julia/require-1-requirements-file`

#### Expected behaviour

Tests should pass

#### Actual behaviour

Example:
```
2024-05-26T11:02:44.4780279Z   Building Conda ──→ `/srv/julia/pkg/packages/Conda/sNGum/deps/build.log`
2024-05-26T11:02:44.4780572Z   Building ZMQ ────→ `/srv/julia/pkg/packages/ZMQ/ItfqT/deps/build.log`
2024-05-26T11:02:44.4780732Z [91m┌ Error: Error building `ZMQ`: 
2024-05-26T11:02:44.4781051Z │ ┌ Warning: platform_key() is deprecated, use platform_key_abi() from now on
2024-05-26T11:02:44.4781170Z │ │   caller = ip:0x0
2024-05-26T11:02:44.4781283Z │ └ @ Core :-1
2024-05-26T11:02:44.4782071Z │ ┌ Warning: Could not extract the platform key of https://github.com/JuliaInterop/ZMQBuilder/releases/download/v4.2.5+6/ZMQ.x86_64-linux-gnu.tar.gz; continuing...
2024-05-26T11:02:44.4782442Z │ └ @ BinaryProvider /srv/julia/pkg/packages/BinaryProvider/U2dKK/src/Prefix.jl:185
2024-05-26T11:02:44.4783477Z │ [ Info: Downloading https://github.com/JuliaInterop/ZMQBuilder/releases/download/v4.2.5+6/ZMQ.x86_64-linux-gnu.tar.gz to /srv/julia/pkg/packages/ZMQ/ItfqT/deps/usr/downloads/ZMQ.x86_64-linux-gnu.tar.gz...
2024-05-26T11:02:44.4784574Z │ ERROR: LoadError: Could not download https://github.com/JuliaInterop/ZMQBuilder/releases/download/v4.2.5+6/ZMQ.x86_64-linux-gnu.tar.gz to /srv/julia/pkg/packages/ZMQ/ItfqT/deps/usr/downloads/ZMQ.x86_64-linux-gnu.tar.gz:
```

https://github.com/JuliaInterop/ZMQBuilder/releases/download/v4.2.5+6/ZMQ.x86_64-linux-gnu.tar.gz does not exist

### How to reproduce

https://github.com/jupyterhub/repo2docker/actions/runs/9242619853/job/25425671430

### PR DESCRIPTION
**Pull request by minrk**
it doesn't work anymore because build dependencies of the old ZMQ.jl have been removed, so I don't see a feasible way for us to keep it working.

xref https://github.com/JuliaInterop/ZMQ.jl/issues/228

closes #1349

### CODE REVIEW

**Comment by minrk** [comment]
Looks like the oldest version of ZMQ.jl that doesn't rely on the removed repo requires Julia 1.3, starting with https://github.com/JuliaInterop/ZMQ.jl/pull/194 . So now Julia 1.3 is the oldest version we can support.

**Comment by minrk** [comment]
fwiw, [julia 1.3](https://github.com/JuliaLang/julia/releases/tag/v1.3.0) is from November 2019, about 4.5 years ago, and the newest version we supported with REQUIRE was [1.1.1](https://github.com/JuliaLang/julia/releases/tag/v1.1.1), just over 5 years ago now.

**Comment by minrk** [comment]
in fact, 1.3-1.5 fail with "No Such Device" in the precompile bind [here](https://github.com/JuliaInterop/ZMQ.jl/blob/bae8c690ec4f701e7ef11096abdeccea8385bfe0/src/ZMQ.jl#L61):

```julia
ZMQ.bind(s1, "tcp://localhost:*")
```

so as it is now, only Julia >= 1.6 will actually work.

The precompile on 1.3-1.5 should be fixed by https://github.com/JuliaInterop/ZMQ.jl/pull/237

**Comment by minrk** [comment]
It would probably behoove us to have frozen base environments for Julia eventually. That wouldn't nave solved the current problem, though.

**Review by manics — APPROVED** [review]
Looks good! https://github.com/JuliaInterop/ZMQ.jl/releases/tag/v1.2.5 was released, so if CI passes this can be merged

**Pull request merged**
