### PR TITLE
Pin doc requirements to avoid CI breakages

### PR DESCRIPTION
**Pull request by manics**
Follow-up to https://github.com/jupyterhub/repo2docker/pull/1050

This pins the versions of all doc dependencies, so we can rely on dependabot to check for problems with updates.

There's no dependabot.yml file in https://github.com/jupyterhub/repo2docker/tree/master/.github but it looks like dependabot has previously opened PRs in this repo: https://github.com/jupyterhub/repo2docker/pulls?q=is%3Apr+author%3Aapp%2Fdependabot+is%3Aclosed

so presumably it's been configured elsewhere?

### CODE REVIEW

**Comment by manics** [comment]
Oops, just seen https://github.com/jupyterhub/repo2docker/pull/1050

**Comment by manics** [comment]
Re-opened with just the version pinning.

**Comment by manics** [comment]
What's the difference between the circleci and readthedocs builds- do we need both?

**Comment by yuvipanda** [comment]
@manics don't think we need both, so I removed CircleCI in https://github.com/jupyterhub/repo2docker/pull/1053

**Pull request merged**
