### PR TITLE
Bump environment

### PR DESCRIPTION
**Pull request by manics**
I thought Id bump repo2docker to JupyterLab 3.1.0.

Decided to bump the rest of the dependencies in `environment.yml` too.... let's see if it works....

### CODE REVIEW

**Review by consideRatio — APPROVED** [review]
I'm not sure about the implications of doing this, but I'm thinking this LGTM

**Comment by meeseeksmachine** [comment]
This pull request has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/what-is-installed-by-default-with-binder/10217/4

**Comment by manics** [comment]
I've updated JupyterLab to 3.1.1

**Comment by consideRatio** [comment]
@betatim or @yuvipanda, with your deeper experience about repo2docker - do we go for merge on this pending upcoming release that manics is preparing?

I dont know much about the implications of merging this.

**Comment by yuvipanda** [comment]
Let's do it!

**Comment by yuvipanda** [comment]
Thanks, @manics and @consideRatio!

**Pull request merged**
