### PR TITLE
Default UI to JupyterLab

### PR DESCRIPTION
**Pull request by SylvainCorlay**
Cf #1026

### CODE REVIEW

**Comment by manics** [comment]
I haven't tried this locally yet, but if I go to `/doc` in mybinder I see just the launch tab, the file browser is closed by default:
image

Can we have it expanded by default? Or would it be better to use `/lab` which automatically displays the file browser?

**Comment by SylvainCorlay** [comment]
We could use `lab` when no filepath is provided and `doc` otherwise? I understand that the demand was to use `doc` (the simple mode) when possible.

**Comment by minrk** [comment]
When I visited `/doc` it opened a notebook, but maybe that was leftover state in my browser. Yeah, if that's the case, maybe let's use `/lab` here and keep `/doc` for filepath in binderhub.

**Comment by manics** [comment]
@SylvainCorlay Sorry for the confusion. I suggested the single document mode in https://github.com/jupyterhub/repo2docker/issues/1026 because I thought it'd be similar to the old notebook: show a single document when you're open a file, show a list of files if not, but that's obviously not how it behaves.

If we're happy with `/lab` are there any benefits to setting `default_url`, or could we change the command to
```py
run_cmd = [
                "jupyter",
                "lab",
...
```
(or `jupyterlab`) instead?

**Comment by minrk** [comment]
> are there any benefits to setting default_url, 

Setting default_url is switching the default *ui* without switching the default *server* implementation to jupyter_server, which starting `jupyter lab` would do. See [this comment](https://github.com/jupyterhub/repo2docker/issues/1026#issuecomment-816454222) for details. It's still something we should do, but has a larger impact on things like extensions.

**Comment by SylvainCorlay** [comment]
Just following up on this. Is there anything blocking this PR ?

**Review by minrk — APPROVED** [review]

**Comment by SylvainCorlay** [comment]
:tada:

**Pull request merged**
