### PR TITLE
Bump version of nodejs

### PR DESCRIPTION
**Pull request by yuvipanda**
16 is also an LTS, and is the current active LTS.

Triggered by code-server package needing a newer version of nodejs!

### CODE REVIEW

**Comment by yuvipanda** [comment]
Can't seem to run freeze.py locally :( Anyone who can do it for me?

**Comment by manics** [comment]
Try https://github.com/jupyterhub/repo2docker/pull/1173

**Comment by yuvipanda** [comment]
@manics yay ty! I've merged that, rebased this on top, ran it and got tests to pass. Thanks for making that PR

**Review by manics — APPROVED** [review]
:tada:

**Pull request merged**
