### PR TITLE
pre-commit: add pyupgrade, isort, and prettier for .md files

### PR DESCRIPTION
**Pull request by consideRatio**
## Summary for reviewers

- pyupgrade, isort, and finally prettier (Markdown autoformatting) was added to pre-commit config
- pre-commit.ci pushed a commit for pyupgrade, isort, and finally prettier
- I added a commit to complement pyupgrade in transitioning to f-strings

Among all changes, I'd say that mainly my manual changes in 15a1fb6 are of importance to reivew as a human I may have made a mistake, but I trust especially pyupgrade and isort to not mess up. I have reviewed my changes and the automated changes quite thoroughly though, and they LGTM.

## Are these extensive changes acceptable?

I think many of us value autoformatting, but it can also cause cause some disruption in PRs etc. I'll be happy to help work mitigate this. I've also ahead of time worked to reduce the amount of open PRs from 35 to 20.

If this is merged, I can also retrospectively add a [.git-blame-ignore](https://github.com/jupyterhub/binderhub/blob/main/.git-blame-ignore-revs) file to help avoid cluttering GitHub's git blame view with formatting changes.

I'd be very thankful if we can go for this even though its a compromise not everyone would like to make, its a big deal for my motivation as a maintainer going forward in this repo having this in place.

### CODE REVIEW

**Comment by consideRatio** [comment]
pre-commit.ci autofix

**Comment by consideRatio** [comment]
pre-commit.ci autofix

**Comment by consideRatio** [comment]
pre-commit.ci autofix

**Review by minrk — APPROVED** [review]

**Comment by yuvipanda** [comment]
Thanks @consideRatio. I assume the markdown prettier is present in other JupyterHub repos too?

**Comment by consideRatio** [comment]
Thanks @yuvipanda and @minrk!!!

Yepp it is, prettier is also used for even more things which I figured was too much for doing in this repo. For example yaml, javascript, json.

z2jh: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/11a5fd7d826ee70260fc0bd16be2ec507b53941b/.pre-commit-config.yaml#L54-L58
jupyterhub: https://github.com/jupyterhub/jupyterhub/blob/54c06c33bdb4f4a9fffc96305d522336a35342c4/.pre-commit-config.yaml#L32-L36

**Pull request merged**
