### PR TITLE
Create Julia projects based on binder/Project.toml when found

### PR DESCRIPTION
**Pull request by frankier**
Closes https://github.com/jupyterhub/repo2docker/issues/1215

### CODE REVIEW

**Comment by frankier** [comment]
Okay I've added a test now. I'm not really sure why coverage has gone down, but maybe this can be merged anyway since it fixes a real bug and has a regression test.

**Comment by consideRatio** [comment]
Nice this LGTM, but I pushed a commit to coalesce the test cases first - was that okay with you?

Our test suite is slow and each added test folder adds ~5 minutes or test execution time or so. In this case, the Julia tests ended up also being the slowest, so by coalescing the tests to one single we ended up with a reduced total duration.

**Comment by frankier** [comment]
Fine by me! Yes I noticed the slowness. Neither Docker nor Julia come for free startup time wise unfortunately!

**Comment by consideRatio** [comment]
It was recently taking ~50 minutes, and work to coalesce tests like this made it go to ~25 minutes :) Thanks for your understanding!

**Pull request merged**
