### PR TITLE
Add entrypoint script which automatically propagates *_PROXY env vars…

### PR DESCRIPTION
**Pull request by g-braeunlich**
… to docker config

### CODE REVIEW

**Review by manics — APPROVED** [review]
This looks good to me- I tested it in a VM.

One thing I noticed is that this configures the proxy for Dockerfile `RUN` commands during docker build, but not for pulling the `FROM` image- I think this can only be changed by configuring the parent docker daemon outside the container which makes sense when you think about it, but it might make the corresponding BinderHub configuration more complicated.

@betatim You're [making a release soon](https://github.com/jupyterhub/repo2docker/pull/1004), are you happy for this to be merged or do you want to wait until after the release?

**Comment by meeseeksmachine** [comment]
This pull request has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/binder-behind-outbound-proxy/7428/5

**Comment by manics** [comment]
@betatim Do you have any concerns with this? Otherwise let's merge it.

**Review by minrk — APPROVED** [review]
Happy to have this change!

I'll just comment for anyone who has concerns about maintaining the generation of valid JSON config produced by `echo`ing lines, repo2docker is in Python so we could write this config file with Python and make it a little simpler, e.g.:

```python
config = {"proxies": {"default": {}}
for env, key in {"HTTP_PROXY": "httpProxy"...}.items():
    value = os.environ.get(env)
    if value:
        config["proxies"]["default"][key] = value

if config["proxies"]["default"]:
    with open(config_path, "w") as f:
        json.dump(config, f)

os.execv(...)
```

**Comment by g-braeunlich** [comment]
Ah, I see. Would you recommend to integrate this into the repo2docker script rather than a entrypoint?

**Comment by minrk** [comment]
> Would you recommend to integrate this into the repo2docker script rather than a entrypoint?

No, I meant that the entrypoint script itself could be in Python if we have issues with this. It's fine as-is, though!

**Pull request merged**
