### PR TITLE
State newly used installation command

### PR DESCRIPTION
**Pull request by fkohrt**

### CODE REVIEW

**Review by manics — APPROVED** [review]
Matches https://github.com/jupyterhub/repo2docker/blob/73ab48a42d8f818038540d0a15bc2b4f7d88d46e/repo2docker/buildpacks/r.py#L380

**Comment by manics** [comment]
Anyone know what's going on with the CircleCI build? Does it do anything the RTD build doesn't?

**Comment by fkohrt** [comment]
Can this be merged?

**Comment by yuvipanda** [comment]
Thanks, @fkohrt!

@manics not sure what's up with CircleCI :(

**Pull request merged**
