### PR TITLE
Rename master branch to main

### PR DESCRIPTION
**Pull request by manics**
Following process from https://github.com/jupyterhub/team-compass/issues/412

## Actions to take, in order:
- [x] approve this PR
- [x] rename the `master` branch to `main` in GitHub (this should automatically update all PRs)
- [x] merge this PR
- [ ] check the publish workflow publishes the expected outputs if relevant
- [ ] If readthedocs.org is used, set main as the default branch explicitly: admin -> advanced -> default branch

## `$ git grep master`
```
.github/workflows/release.yml:        uses: pypa/gh-action-pypi-publish@master
```
External action

```
docs/source/conf.py:# The master toctree document.
docs/source/conf.py:master_doc = "index"
docs/source/conf.py:        master_doc,
docs/source/conf.py:man_pages = [(master_doc, "repo2docker", "repo2docker Documentation", [author], 1)]
docs/source/conf.py:        master_doc,
```
Sphinx stuff

```
repo2docker/_version.py:        # "stabilization", as well as "HEAD" and "master".
```
Versioneer stuff

```
repo2docker/contentproviders/git.py:                if ref == "master":
repo2docker/contentproviders/git.py:                        "Failed to check out the 'master' branch. "
repo2docker/contentproviders/git.py:                        "Maybe the default branch is not named 'master' "
```
Explicit handling of `master`

```
repo2docker/utils.py:    https://github.com/docker/distribution/blob/master/reference/regexp.go
repo2docker/utils.py:        https://github.com/docker/distribution/blob/master/reference/regexp.go
```
External references

```
tests/conftest.py:    """Create a git repository with a git submodule in a non-master branch.
tests/conftest.py:    submodules are initialized properly when the master branch doesn't have
tests/external/reproductions.repos.yaml:  ref: origin/master
tests/external/reproductions.repos.yaml:  ref: master
tests/unit/contentproviders/test_git.py:    # indeed doesn't get any submodule, even though they are in master
tests/unit/test_clone_depth.py:    """Test a remote repository, with a refspec of 'master'"""
tests/unit/test_clone_depth.py:            ref="master",
tests/unit/test_clone_depth.py:    """Test a remote repository, with a refspec of the master commit hash"""
tests/unit/test_utils.py:            "--editable=git+https://github.com/popgensims/stdpopsim.git#egg=stdpopsim-master",
```
I've avoided changing anything under tests since it'll require code review to ensure we don't inadvertently remove a test case.

```
versioneer.py:(https://travis-ci.org/warner/python-versioneer.png?branch=master)
versioneer.py:  "master" and "slave" subprojects, each with their own `setup.py`,
versioneer.py:        # "stabilization", as well as "HEAD" and "master".
versioneer.py:        # "stabilization", as well as "HEAD" and "master".
```
Versioneer stuff

### CODE REVIEW

**Review by consideRatio — COMMENTED** [review]
Two suggestions, but otherwise this LGTM!

```
.github/workflows/release.yml:        uses: pypa/gh-action-pypi-publish@master
```

This can be `@HEAD` as well right?

```
docs/source/conf.py:# The master toctree document.
docs/source/conf.py:master_doc = "index"
docs/source/conf.py:        master_doc,
docs/source/conf.py:man_pages = [(master_doc, "repo2docker", "repo2docker Documentation", [author], 1)]
docs/source/conf.py:        master_doc,
```

root_doc is now an option to master_doc supported by a modern version of sphinx, so setting both is a compatibility strategy for us to use in order to migrate away from master_doc.

```
# The root toctree document.
root_doc = master_doc = "index"
```

**Comment by manics** [comment]
Thanks, I've updated the Sphinx conf.py.

I'm a bit hesistant to change a critical GitHub action to use HEAD without an official statement from the maintainers. We could switch to commit hashes or tags and rely on dependabot to bump them instead, which also means we'd be fully aware of any changes. Alternatively we could switch to `release/v1`?

**Review by consideRatio — APPROVED** [review]
I saw a build error, but this is 100% documentation so go for it

**Comment by manics** [comment]
Thanks @consideRatio.

Let's go for it then! I don't have permission to rename the branch.

**Comment by consideRatio** [comment]
Branch renamed!

**Comment by manics** [comment]
Thanks! Do you know who's got access to readthedocs to check the branch name?
The Docker Hub artifact has been broken for a while, see https://github.com/jupyterhub/repo2docker/pull/1071

**Comment by consideRatio** [comment]
@manics from https://readthedocs.org/projects/repo2docker/ I conclude among others @yuvipanda @choldgraf have access to update the readthedocs to not be coupled to the master branch, but instead to the main branch.

**Comment by choldgraf** [comment]
done 👍

**Pull request merged**
