### PR TITLE
Bump default R version to 4.2 from 4.1, and let R 3.4 go from 3.4.0 to 3.4.4

### PR DESCRIPTION
**Pull request by yuvipanda**
Been out for a bit now

### CODE REVIEW

**Comment by consideRatio** [comment]
Test failure was relevant, related to the R version.

Makes sense to me otherwise!

**Comment by consideRatio** [comment]
@yuvipanda I pushed two commits, what do you think?

**Comment by yuvipanda** [comment]
@consideRatio i love it! Ready to merge I think.

**Comment by consideRatio** [comment]
🥳🥳🥳

**Pull request merged**
