### PR TITLE
[MRG] Release 2021.08.0

### PR DESCRIPTION
**Pull request by manics**
It's about time we had a release! This also adds changelogs for the previous two releases (`2021.01.0` and `2021.03.0`)

### CODE REVIEW

**Comment by consideRatio** [comment]
repo2docker fails to install because of #1064 isn't released currently. Further in some context where `six` insn't available, it will also fail by being dependant on docker where docker in turn has a critical regression in 5.0.0 where that I workaround in https://github.com/jupyterhub/repo2docker/pull/1066.

I think we should workaround that issue by merging #1066 before this release, because docker-py is so under-maintained that no release seem to happen causing many dependent projects to fail.

**Comment by manics** [comment]
We need https://github.com/jupyterhub/repo2docker/pull/1071 or something similar to fix the Docker build, then I think we can release!

**Comment by manics** [comment]
Any last minute issues? Otherwise I'll tag!

**Comment by consideRatio** [comment]
Excellent work on this @manics!!! :heart:!

This LGTM! How did you do the changelog in RST format?

**Comment by manics** [comment]
`github-activity` followed by a regex search and replace with backreferences 😃

**Pull request merged**
